Library feature
alishabab/javascript-library pull request #2
Opened 2020-07-14 07:57 UTC by ikraamg

2020-07-14 12:58 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-07-14 12:58 UTC, bellom commented on index.html
> +    <button type="submit" id= 'create'>Create Book</button> -->
. It’s better to delete commented code. If you need to review a previous version of your code, use git history. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-07-14 12:58 UTC, bellom commented on library.js
> +};
Let's separate the DOM from application logic, you can create another file for DOM.

![image](https://user-images.githubusercontent.com/31897434/73420341-70e18b80-4322-11ea-840a-fa14e04b592b.png)

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59623451/

2020-07-14 12:58 UTC, bellom commented on library.js
> +  <button type="submit" id= 'create'>Create Book</button>`;
You need to do form controls to make sure empty forms cannot be submitted
![image](https://user-images.githubusercontent.com/31897434/87428234-f2c82700-c5d9-11ea-883d-7920b82f0343.png)

2020-07-15 04:57 UTC, bellom requested changes
## Hi Team  :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-07-15 04:57 UTC, bellom commented on index.html
> +      <button type="submit" id="create">Create Book</button>
Opps, i don't think you were having this issue before..... 🤔 
Kindly clear the form once the user creates a book.
(I need to clear the form manually to add a new book.)
![image](https://user-images.githubusercontent.com/31897434/87504556-be4a7e80-c65e-11ea-99b9-50312c8f43b0.png)

2020-07-15 04:57 UTC, bellom commented on js/dom.js
> +    window.alert('Title/Author/Pages must not be empty');
Opps 🤦‍♂️ , This should be production code, we shouldn't have `alert`, please remove the `alert`.
If you don't want to pop-up new div message, I think you can make use of `required` on the inputs tags.

2020-07-15 07:47 UTC, fatymahmed approved these changes
## Hi @ikraamg @alishabab,
Good job implementing the changes 🎉🎉

## Status: Approved ✔️
_You may go ahead and merge this PR_

2020-07-15 07:54 UTC, merged